### ISSUE TITLE
Filler rooms/rooms smaller than minimum size aren't working properly

### ISSUE THREAD

**Issue by thegur90** [CelestialCartographers/Loenn#12] opened 2022-01-06 19:01 UTC
to recreate-
option A: create a 40x23 room and try dragging it to be smaller, will be unsuccesful
option b: create a 40x23 room and then edit it's settings via room>configure (ofc attempt a smaller size), will also be unsuccesful

**Comment by Cruor** [comment] 2022-01-07 10:18
This is currently the intended behaviour
Was hoping to actually get proper filler support added instead of relying on tiny normal rooms, but that is still work in progress.
Will probably add a prompt for making it smaller than recommend in room window like Ahorn has at some point.

**Comment by Cruor** [comment] 2023-07-14 12:03
Added the support for this with holding ctrl and resizing the room. Keeping the issue open because the room window still doesn't allow this, if it even should.

**Comment by Cruor** [comment] 2024-05-25 15:46
Fixed in room window as well, considering this complete.

**Closed by Cruor** 2024-05-25 15:46 UTC
