### ISSUE TITLE
Tiles Do Not Properly Update When Using the Rectangle Tool

### ISSUE THREAD

**Issue by Spekio** [CelestialCartographers/Loenn#14] opened 2022-01-23 21:13 UTC
When drawing with the rectangle tool, the newly drawn tiles do not always show properly. It seems to happen when you release the mouse on the same pixel that adds the next tile to the side or below. The rectangle will show more area than is displayed when you release the mouse. The tile is actually there, but won't show up until after you place another tile. See video for an example.

https://user-images.githubusercontent.com/7883073/150698106-74609aad-a6c1-4b97-8973-e3d37dcd4123.mp4

**Comment by Cruor** [comment] 2022-01-25 18:21
I can only reproduce this with mouse keys really, because it seems to spit out more mouse events than expected 🤔
How are you reproducing this yourself? I can totally see this happen with extremely fast mouse inputs between render events, but its quite weird.

**Comment by Cruor** [comment] 2022-01-25 18:32
Seems to be a mousekeys issue actually, you should be hitting right arrow and not 5... Its not actually pixel perfect, its completely a timing issue 😅 
Thanks for the reproduction steps though, it is now fixed in commit de55cfd

**Closed by Cruor** 2022-01-25 18:32 UTC
