### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by BogdanRogatyk** [CelestialCartographers/Loenn#67] opened 2024-03-15 16:57 UTC
Error

Editor version: 0.7.8
Love2d version: 11.4.0 - Mysterious Mysteries
Operating system: Windows

utils/filesystem.lua:40: invalid value (nil) at index 1 in table for 'concat'

Traceback

[love "callbacks.lua"]:228: in function 'handler'
[C]: in function 'concat'
utils/filesystem.lua:40: in function 'joinpath'
celeste_render.lua:24: in function 'f'
selene/selene/wrappers/searcher/love2d/searcher.lua:16: in function <selene/selene/wrappers/searcher/love2d/searcher.lua:13>
[C]: in function 'require'
loaded_state.lua:4: in function 'f'
selene/selene/wrappers/searcher/love2d/searcher.lua:16: in function <selene/selene/wrappers/searcher/love2d/searcher.lua:13>
[C]: in function 'require'
tool_utils.lua:1: in function 'f'
...
scenes/loading.lua:40: in function 'firstEnter'
scene_handler.lua:126: in function 'changeScene'
scenes/startup.lua:34: in function 'saveGotoLoading'
scenes/startup.lua:47: in function 'func'
utils/threads.lua:32: in function 'runFunctionOnData'
utils/threads.lua:48: in function 'update'
selene_main.lua:39: in function 'update'
main.lua:61: in function <main.lua:25>
[C]: in function 'xpcall'
I hope I get an answer, I really want to map...

**Comment by Cruor** [comment] 2024-03-15 17:00
Duplicate of https://github.com/CelestialCartographers/Loenn/issues/56
The comments on that issue should potentially fix the issue for you.

**Closed by Cruor** 2024-03-15 17:00 UTC
