### ISSUE TITLE
Loenn crashes when trying to open(any version)

### ISSUE THREAD

**Issue by LipeGRS** [CelestialCartographers/Loenn#55] opened 2023-07-23 00:11 UTC
Hey there! I am having some troubles with Loenn. The program keeps crashing when booting up, no matter what I do. Here is the error in question:
Error

Editor version: 0.7.4
Love2d version: 11.4.0 - Mysterious Mysteries
Operating system: Windows

utils/filesystem.lua:40: invalid value (nil) at index 1 in table for 'concat'

Traceback

[love "callbacks.lua"]:228: in function 'handler'
[C]: in function 'concat'
utils/filesystem.lua:40: in function 'joinpath'
celeste_render.lua:24: in function 'f'
selene/selene/wrappers/searcher/love2d/searcher.lua:16: in function <selene/selene/wrappers/searcher/love2d/searcher.lua:13>
[C]: in function 'require'
loaded_state.lua:4: in function 'f'
selene/selene/wrappers/searcher/love2d/searcher.lua:16: in function <selene/selene/wrappers/searcher/love2d/searcher.lua:13>
[C]: in function 'require'
tool_utils.lua:1: in function 'f'
...
[C]: in function 'require'
scenes/loading.lua:40: in function 'firstEnter'
scene_handler.lua:124: in function 'changeScene'
scenes/startup.lua:34: in function 'saveGotoLoading'
scenes/startup.lua:114: in function <scenes/startup.lua:109>
scene_handler.lua:46: in function 'update'
selene_main.lua:38: in function 'update'
main.lua:61: in function <main.lua:25>
[C]: in function 'xpcall'

This error appears whenever I try to open the program, and a folder on %localappdata% is not even created. Could someone please help me? Thanks!

**Comment by Cruor** [comment] 2023-10-07 08:59
Duplicate of https://github.com/CelestialCartographers/Loenn/issues/56
That should have a workaround for your issue.

**Closed by Cruor** 2023-10-07 08:59 UTC
